version: '3.9'

services:
  stroer-task:
    container_name: stroer-task
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      -  ./output:/usr/local/lib/output
    depends_on:
      - redis

  redis:
    container_name: my-local-redis
    image: redis:latest
    ports:
      - "6379:6379"