spring:
  application:
    name: "Ströer labs - interview task"
  config:
    import: "optional:file:./application-local.yml"

server:
  port : 8080

storage:
  flat-file:
    path: "output/output.json"

redis-conf:
  host: localhost
  port: 6379
